### ISSUE TITLE
Unpublish from npm registry

### ISSUE THREAD

**Issue by tysongach** [tmrudick/tonic#6]
Hi!

Since this project has been renamed to Tonic, would you be up for [un-publishing](https://docs.npmjs.com/cli/unpublish) it under the “Bourbon” name on the npm registry? I help maintain the [Bourbon Sass library](http://bourbon.io) and we have some confused people about why we don’t have Bourbon published there.

Thanks so much.

**Comment by tysongach** [comment]
@tmrudick Any word on this?

**Comment by tmrudick** [comment]
Done.

**Comment by tysongach** [comment]
@tmrudick Thanks!
